
services: 
  cred-db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - cred-pgdata:/var/lib/postgresql/data

  credpal-service:
    image: ghcr.io/vakabinto/CredPal-Assesment101/credpal-service:${TAG}
    container_name: credpal-service
    env_file:
      - .env
    environment:
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_PORT=5432
    depends_on:
      - cred-db

volumes:
  cred-pgdata:
